name: World1-6TrafficLights
version: 1.0
main: com.andrew121410.mc.world16trafficlights.World16TrafficLights
api-version: 1.16
authors: [Andrew121410]
description: A traffic light plugin that i made for private mc server

depend:
  - World1-6Utils

commands:
  trafficlight:
    permission: world16trafficlights.trafficlight
    description: lets you do the traffic light command

permissions:
  world16trafficlights.trafficlight:
    description: lets you do the traffic light command
    default: op