name: Java CI with Maven

on:
  push:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4 # https://github.com/actions/checkout

      - name: Set up JDK 21 # https://github.com/actions/setup-java
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven

      - name: Build with Maven
        run: mvn package

      - name: Generate sha256sum
        run: sha256sum target/World1-6TrafficLights.jar >> hash.txt

      - name: Deploy Release With Artifact
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          prerelease: false
          files: |
            target/World1-6TrafficLights.jar
            hash.txt